name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: windows-latest
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      - name: today date is
        run: |
          date
      - name: directory content
        run: |
          lc
