name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: windows-latest
    steps:
      - name: Say hello
        run: |
          Write-Output "Hello World!"
